//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSPlataforma.DA.PEWSGeneralReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEWSConsultarCIPRequestMod1", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BEWSConsultarCIPRequestMod1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodServField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIPSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoRequestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CodServ {
            get {
                return this.CodServField;
            }
            set {
                if ((object.ReferenceEquals(this.CodServField, value) != true)) {
                    this.CodServField = value;
                    this.RaisePropertyChanged("CodServ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Firma {
            get {
                return this.FirmaField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaField, value) != true)) {
                    this.FirmaField = value;
                    this.RaisePropertyChanged("Firma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CIPS {
            get {
                return this.CIPSField;
            }
            set {
                if ((object.ReferenceEquals(this.CIPSField, value) != true)) {
                    this.CIPSField = value;
                    this.RaisePropertyChanged("CIPS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string InfoRequest {
            get {
                return this.InfoRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoRequestField, value) != true)) {
                    this.InfoRequestField = value;
                    this.RaisePropertyChanged("InfoRequest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEWSConsultarCIPResponseMod1", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BEWSConsultarCIPResponseMod1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string XML {
            get {
                return this.XMLField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLField, value) != true)) {
                    this.XMLField = value;
                    this.RaisePropertyChanged("XML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string InfoResponse {
            get {
                return this.InfoResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoResponseField, value) != true)) {
                    this.InfoResponseField = value;
                    this.RaisePropertyChanged("InfoResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEWSActualizaCIPRequestMod1", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BEWSActualizaCIPRequestMod1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodServField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIPField;
        
        private System.DateTime FechaExpiraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoRequestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CodServ {
            get {
                return this.CodServField;
            }
            set {
                if ((object.ReferenceEquals(this.CodServField, value) != true)) {
                    this.CodServField = value;
                    this.RaisePropertyChanged("CodServ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Firma {
            get {
                return this.FirmaField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaField, value) != true)) {
                    this.FirmaField = value;
                    this.RaisePropertyChanged("Firma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CIP {
            get {
                return this.CIPField;
            }
            set {
                if ((object.ReferenceEquals(this.CIPField, value) != true)) {
                    this.CIPField = value;
                    this.RaisePropertyChanged("CIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime FechaExpira {
            get {
                return this.FechaExpiraField;
            }
            set {
                if ((this.FechaExpiraField.Equals(value) != true)) {
                    this.FechaExpiraField = value;
                    this.RaisePropertyChanged("FechaExpira");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string InfoRequest {
            get {
                return this.InfoRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoRequestField, value) != true)) {
                    this.InfoRequestField = value;
                    this.RaisePropertyChanged("InfoRequest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEWSActualizaCIPResponseMod1", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BEWSActualizaCIPResponseMod1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string InfoResponse {
            get {
                return this.InfoResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoResponseField, value) != true)) {
                    this.InfoResponseField = value;
                    this.RaisePropertyChanged("InfoResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEWSElimCIPRequestMod1", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BEWSElimCIPRequestMod1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodServField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoRequestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CodServ {
            get {
                return this.CodServField;
            }
            set {
                if ((object.ReferenceEquals(this.CodServField, value) != true)) {
                    this.CodServField = value;
                    this.RaisePropertyChanged("CodServ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Firma {
            get {
                return this.FirmaField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaField, value) != true)) {
                    this.FirmaField = value;
                    this.RaisePropertyChanged("Firma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CIP {
            get {
                return this.CIPField;
            }
            set {
                if ((object.ReferenceEquals(this.CIPField, value) != true)) {
                    this.CIPField = value;
                    this.RaisePropertyChanged("CIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string InfoRequest {
            get {
                return this.InfoRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoRequestField, value) != true)) {
                    this.InfoRequestField = value;
                    this.RaisePropertyChanged("InfoRequest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEWSElimCIPResponseMod1", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BEWSElimCIPResponseMod1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string InfoResponse {
            get {
                return this.InfoResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoResponseField, value) != true)) {
                    this.InfoResponseField = value;
                    this.RaisePropertyChanged("InfoResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEWSGenCIPRequestMod1", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BEWSGenCIPRequestMod1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodServField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CodServ {
            get {
                return this.CodServField;
            }
            set {
                if ((object.ReferenceEquals(this.CodServField, value) != true)) {
                    this.CodServField = value;
                    this.RaisePropertyChanged("CodServ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Firma {
            get {
                return this.FirmaField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaField, value) != true)) {
                    this.FirmaField = value;
                    this.RaisePropertyChanged("Firma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Xml {
            get {
                return this.XmlField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlField, value) != true)) {
                    this.XmlField = value;
                    this.RaisePropertyChanged("Xml");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEWSGenCIPResponseMod1", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BEWSGenCIPResponseMod1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Xml {
            get {
                return this.XmlField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlField, value) != true)) {
                    this.XmlField = value;
                    this.RaisePropertyChanged("Xml");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEWSConsultarSolicitudRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BEWSConsultarSolicitudRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cServField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cServ {
            get {
                return this.cServField;
            }
            set {
                if ((object.ReferenceEquals(this.cServField, value) != true)) {
                    this.cServField = value;
                    this.RaisePropertyChanged("cServ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CClave {
            get {
                return this.CClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.CClaveField, value) != true)) {
                    this.CClaveField = value;
                    this.RaisePropertyChanged("CClave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Xml {
            get {
                return this.XmlField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlField, value) != true)) {
                    this.XmlField = value;
                    this.RaisePropertyChanged("Xml");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEWSConsultarSolicitudResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BEWSConsultarSolicitudResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Xml {
            get {
                return this.XmlField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlField, value) != true)) {
                    this.XmlField = value;
                    this.RaisePropertyChanged("Xml");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PEWSGeneralReference.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento request del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarCIPMod1", ReplyAction="*")]
        WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1Response ConsultarCIPMod1(WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarCIPMod1", ReplyAction="*")]
        System.Threading.Tasks.Task<WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1Response> ConsultarCIPMod1Async(WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento request del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCIPMod1", ReplyAction="*")]
        WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1Response ActualizarCIPMod1(WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCIPMod1", ReplyAction="*")]
        System.Threading.Tasks.Task<WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1Response> ActualizarCIPMod1Async(WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento request del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarCIPMod1", ReplyAction="*")]
        WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1Response EliminarCIPMod1(WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarCIPMod1", ReplyAction="*")]
        System.Threading.Tasks.Task<WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1Response> EliminarCIPMod1Async(WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento request del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarCIPMod1", ReplyAction="*")]
        WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1Response GenerarCIPMod1(WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarCIPMod1", ReplyAction="*")]
        System.Threading.Tasks.Task<WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1Response> GenerarCIPMod1Async(WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento request del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarSolicitudPagov2", ReplyAction="*")]
        WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2Response ConsultarSolicitudPagov2(WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarSolicitudPagov2", ReplyAction="*")]
        System.Threading.Tasks.Task<WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2Response> ConsultarSolicitudPagov2Async(WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarCIPMod1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarCIPMod1", Namespace="http://tempuri.org/", Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1RequestBody Body;
        
        public ConsultarCIPMod1Request() {
        }
        
        public ConsultarCIPMod1Request(WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarCIPMod1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.BEWSConsultarCIPRequestMod1 request;
        
        public ConsultarCIPMod1RequestBody() {
        }
        
        public ConsultarCIPMod1RequestBody(WSPlataforma.DA.PEWSGeneralReference.BEWSConsultarCIPRequestMod1 request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarCIPMod1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarCIPMod1Response", Namespace="http://tempuri.org/", Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1ResponseBody Body;
        
        public ConsultarCIPMod1Response() {
        }
        
        public ConsultarCIPMod1Response(WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarCIPMod1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.BEWSConsultarCIPResponseMod1 ConsultarCIPMod1Result;
        
        public ConsultarCIPMod1ResponseBody() {
        }
        
        public ConsultarCIPMod1ResponseBody(WSPlataforma.DA.PEWSGeneralReference.BEWSConsultarCIPResponseMod1 ConsultarCIPMod1Result) {
            this.ConsultarCIPMod1Result = ConsultarCIPMod1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarCIPMod1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarCIPMod1", Namespace="http://tempuri.org/", Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1RequestBody Body;
        
        public ActualizarCIPMod1Request() {
        }
        
        public ActualizarCIPMod1Request(WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarCIPMod1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.BEWSActualizaCIPRequestMod1 request;
        
        public ActualizarCIPMod1RequestBody() {
        }
        
        public ActualizarCIPMod1RequestBody(WSPlataforma.DA.PEWSGeneralReference.BEWSActualizaCIPRequestMod1 request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarCIPMod1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarCIPMod1Response", Namespace="http://tempuri.org/", Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1ResponseBody Body;
        
        public ActualizarCIPMod1Response() {
        }
        
        public ActualizarCIPMod1Response(WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarCIPMod1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.BEWSActualizaCIPResponseMod1 ActualizarCIPMod1Result;
        
        public ActualizarCIPMod1ResponseBody() {
        }
        
        public ActualizarCIPMod1ResponseBody(WSPlataforma.DA.PEWSGeneralReference.BEWSActualizaCIPResponseMod1 ActualizarCIPMod1Result) {
            this.ActualizarCIPMod1Result = ActualizarCIPMod1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarCIPMod1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarCIPMod1", Namespace="http://tempuri.org/", Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1RequestBody Body;
        
        public EliminarCIPMod1Request() {
        }
        
        public EliminarCIPMod1Request(WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarCIPMod1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.BEWSElimCIPRequestMod1 request;
        
        public EliminarCIPMod1RequestBody() {
        }
        
        public EliminarCIPMod1RequestBody(WSPlataforma.DA.PEWSGeneralReference.BEWSElimCIPRequestMod1 request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarCIPMod1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarCIPMod1Response", Namespace="http://tempuri.org/", Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1ResponseBody Body;
        
        public EliminarCIPMod1Response() {
        }
        
        public EliminarCIPMod1Response(WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarCIPMod1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.BEWSElimCIPResponseMod1 EliminarCIPMod1Result;
        
        public EliminarCIPMod1ResponseBody() {
        }
        
        public EliminarCIPMod1ResponseBody(WSPlataforma.DA.PEWSGeneralReference.BEWSElimCIPResponseMod1 EliminarCIPMod1Result) {
            this.EliminarCIPMod1Result = EliminarCIPMod1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarCIPMod1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarCIPMod1", Namespace="http://tempuri.org/", Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1RequestBody Body;
        
        public GenerarCIPMod1Request() {
        }
        
        public GenerarCIPMod1Request(WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerarCIPMod1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.BEWSGenCIPRequestMod1 request;
        
        public GenerarCIPMod1RequestBody() {
        }
        
        public GenerarCIPMod1RequestBody(WSPlataforma.DA.PEWSGeneralReference.BEWSGenCIPRequestMod1 request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarCIPMod1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarCIPMod1Response", Namespace="http://tempuri.org/", Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1ResponseBody Body;
        
        public GenerarCIPMod1Response() {
        }
        
        public GenerarCIPMod1Response(WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerarCIPMod1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.BEWSGenCIPResponseMod1 GenerarCIPMod1Result;
        
        public GenerarCIPMod1ResponseBody() {
        }
        
        public GenerarCIPMod1ResponseBody(WSPlataforma.DA.PEWSGeneralReference.BEWSGenCIPResponseMod1 GenerarCIPMod1Result) {
            this.GenerarCIPMod1Result = GenerarCIPMod1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarSolicitudPagov2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarSolicitudPagov2", Namespace="http://tempuri.org/", Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2RequestBody Body;
        
        public ConsultarSolicitudPagov2Request() {
        }
        
        public ConsultarSolicitudPagov2Request(WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarSolicitudPagov2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.BEWSConsultarSolicitudRequest request;
        
        public ConsultarSolicitudPagov2RequestBody() {
        }
        
        public ConsultarSolicitudPagov2RequestBody(WSPlataforma.DA.PEWSGeneralReference.BEWSConsultarSolicitudRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarSolicitudPagov2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarSolicitudPagov2Response", Namespace="http://tempuri.org/", Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2ResponseBody Body;
        
        public ConsultarSolicitudPagov2Response() {
        }
        
        public ConsultarSolicitudPagov2Response(WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarSolicitudPagov2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSPlataforma.DA.PEWSGeneralReference.BEWSConsultarSolicitudResponse ConsultarSolicitudPagov2Result;
        
        public ConsultarSolicitudPagov2ResponseBody() {
        }
        
        public ConsultarSolicitudPagov2ResponseBody(WSPlataforma.DA.PEWSGeneralReference.BEWSConsultarSolicitudResponse ConsultarSolicitudPagov2Result) {
            this.ConsultarSolicitudPagov2Result = ConsultarSolicitudPagov2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : WSPlataforma.DA.PEWSGeneralReference.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<WSPlataforma.DA.PEWSGeneralReference.ServiceSoap>, WSPlataforma.DA.PEWSGeneralReference.ServiceSoap {
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) :
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<PEWSGeneralReference.ConsultarCIPMod1Response> ConsultarCIPMod1Async(PEWSGeneralReference.ConsultarCIPMod1Request request)
        {
            return base.Channel.ConsultarCIPMod1Async(request);
        }

        public System.Threading.Tasks.Task<PEWSGeneralReference.ActualizarCIPMod1Response> ActualizarCIPMod1Async(PEWSGeneralReference.ActualizarCIPMod1Request request)
        {
            return base.Channel.ActualizarCIPMod1Async(request);
        }

        public System.Threading.Tasks.Task<PEWSGeneralReference.EliminarCIPMod1Response> EliminarCIPMod1Async(PEWSGeneralReference.EliminarCIPMod1Request request)
        {
            return base.Channel.EliminarCIPMod1Async(request);
        }

        public System.Threading.Tasks.Task<PEWSGeneralReference.GenerarCIPMod1Response> GenerarCIPMod1Async(PEWSGeneralReference.GenerarCIPMod1Request request)
        {
            return base.Channel.GenerarCIPMod1Async(request);
        }

        public System.Threading.Tasks.Task<PEWSGeneralReference.ConsultarSolicitudPagov2Response> ConsultarSolicitudPagov2Async(PEWSGeneralReference.ConsultarSolicitudPagov2Request request)
        {
            return base.Channel.ConsultarSolicitudPagov2Async(request);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://pre1a.pagoefectivo.pe/PagoEfectivoWSGeneralv2/service.asmx"); //desarrollo
                //return new System.ServiceModel.EndpointAddress("http://cip.pagoefectivo.pe/PagoEfectivoWSGeneralv2/service.asmx"); // produccion
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                //return new System.ServiceModel.EndpointAddress("http://pre1a.pagoefectivo.pe/PagoEfectivoWSGeneralv2/service.asmx"); //desarrollo
                return new System.ServiceModel.EndpointAddress("http://cip.pagoefectivo.pe/PagoEfectivoWSGeneralv2/service.asmx"); // produccion
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        public enum EndpointConfiguration
        {

            ServiceSoap,

            ServiceSoap12,
        }

        //public ServiceSoapClient() {
        //}
        
        //public ServiceSoapClient(string endpointConfigurationName) : 
        //        base(endpointConfigurationName) {
        //}
        
        //public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
        //        base(endpointConfigurationName, remoteAddress) {
        //}
        
        //public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
        //        base(endpointConfigurationName, remoteAddress) {
        //}
        
        //public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
        //        base(binding, remoteAddress) {
        //}
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1Response WSPlataforma.DA.PEWSGeneralReference.ServiceSoap.ConsultarCIPMod1(WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1Request request) {
            return base.Channel.ConsultarCIPMod1(request);
        }
        
        public WSPlataforma.DA.PEWSGeneralReference.BEWSConsultarCIPResponseMod1 ConsultarCIPMod1(WSPlataforma.DA.PEWSGeneralReference.BEWSConsultarCIPRequestMod1 request) {
            WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1Request inValue = new WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1Request();
            inValue.Body = new WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1RequestBody();
            inValue.Body.request = request;
            WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1Response retVal = ((WSPlataforma.DA.PEWSGeneralReference.ServiceSoap)(this)).ConsultarCIPMod1(inValue);
            return retVal.Body.ConsultarCIPMod1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1Response> WSPlataforma.DA.PEWSGeneralReference.ServiceSoap.ConsultarCIPMod1Async(WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1Request request) {
            return base.Channel.ConsultarCIPMod1Async(request);
        }
        
        public System.Threading.Tasks.Task<WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1Response> ConsultarCIPMod1Async(WSPlataforma.DA.PEWSGeneralReference.BEWSConsultarCIPRequestMod1 request) {
            WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1Request inValue = new WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1Request();
            inValue.Body = new WSPlataforma.DA.PEWSGeneralReference.ConsultarCIPMod1RequestBody();
            inValue.Body.request = request;
            return ((WSPlataforma.DA.PEWSGeneralReference.ServiceSoap)(this)).ConsultarCIPMod1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1Response WSPlataforma.DA.PEWSGeneralReference.ServiceSoap.ActualizarCIPMod1(WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1Request request) {
            return base.Channel.ActualizarCIPMod1(request);
        }
        
        public WSPlataforma.DA.PEWSGeneralReference.BEWSActualizaCIPResponseMod1 ActualizarCIPMod1(WSPlataforma.DA.PEWSGeneralReference.BEWSActualizaCIPRequestMod1 request) {
            WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1Request inValue = new WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1Request();
            inValue.Body = new WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1RequestBody();
            inValue.Body.request = request;
            WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1Response retVal = ((WSPlataforma.DA.PEWSGeneralReference.ServiceSoap)(this)).ActualizarCIPMod1(inValue);
            return retVal.Body.ActualizarCIPMod1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1Response> WSPlataforma.DA.PEWSGeneralReference.ServiceSoap.ActualizarCIPMod1Async(WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1Request request) {
            return base.Channel.ActualizarCIPMod1Async(request);
        }
        
        public System.Threading.Tasks.Task<WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1Response> ActualizarCIPMod1Async(WSPlataforma.DA.PEWSGeneralReference.BEWSActualizaCIPRequestMod1 request) {
            WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1Request inValue = new WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1Request();
            inValue.Body = new WSPlataforma.DA.PEWSGeneralReference.ActualizarCIPMod1RequestBody();
            inValue.Body.request = request;
            return ((WSPlataforma.DA.PEWSGeneralReference.ServiceSoap)(this)).ActualizarCIPMod1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1Response WSPlataforma.DA.PEWSGeneralReference.ServiceSoap.EliminarCIPMod1(WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1Request request) {
            return base.Channel.EliminarCIPMod1(request);
        }
        
        public WSPlataforma.DA.PEWSGeneralReference.BEWSElimCIPResponseMod1 EliminarCIPMod1(WSPlataforma.DA.PEWSGeneralReference.BEWSElimCIPRequestMod1 request) {
            WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1Request inValue = new WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1Request();
            inValue.Body = new WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1RequestBody();
            inValue.Body.request = request;
            WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1Response retVal = ((WSPlataforma.DA.PEWSGeneralReference.ServiceSoap)(this)).EliminarCIPMod1(inValue);
            return retVal.Body.EliminarCIPMod1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1Response> WSPlataforma.DA.PEWSGeneralReference.ServiceSoap.EliminarCIPMod1Async(WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1Request request) {
            return base.Channel.EliminarCIPMod1Async(request);
        }
        
        public System.Threading.Tasks.Task<WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1Response> EliminarCIPMod1Async(WSPlataforma.DA.PEWSGeneralReference.BEWSElimCIPRequestMod1 request) {
            WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1Request inValue = new WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1Request();
            inValue.Body = new WSPlataforma.DA.PEWSGeneralReference.EliminarCIPMod1RequestBody();
            inValue.Body.request = request;
            return ((WSPlataforma.DA.PEWSGeneralReference.ServiceSoap)(this)).EliminarCIPMod1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1Response WSPlataforma.DA.PEWSGeneralReference.ServiceSoap.GenerarCIPMod1(WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1Request request) {
            return base.Channel.GenerarCIPMod1(request);
        }
        
        public WSPlataforma.DA.PEWSGeneralReference.BEWSGenCIPResponseMod1 GenerarCIPMod1(WSPlataforma.DA.PEWSGeneralReference.BEWSGenCIPRequestMod1 request) {
            WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1Request inValue = new WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1Request();
            inValue.Body = new WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1RequestBody();
            inValue.Body.request = request;
            WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1Response retVal = ((WSPlataforma.DA.PEWSGeneralReference.ServiceSoap)(this)).GenerarCIPMod1(inValue);
            return retVal.Body.GenerarCIPMod1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1Response> WSPlataforma.DA.PEWSGeneralReference.ServiceSoap.GenerarCIPMod1Async(WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1Request request) {
            return base.Channel.GenerarCIPMod1Async(request);
        }
        
        public System.Threading.Tasks.Task<WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1Response> GenerarCIPMod1Async(WSPlataforma.DA.PEWSGeneralReference.BEWSGenCIPRequestMod1 request) {
            WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1Request inValue = new WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1Request();
            inValue.Body = new WSPlataforma.DA.PEWSGeneralReference.GenerarCIPMod1RequestBody();
            inValue.Body.request = request;
            return ((WSPlataforma.DA.PEWSGeneralReference.ServiceSoap)(this)).GenerarCIPMod1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2Response WSPlataforma.DA.PEWSGeneralReference.ServiceSoap.ConsultarSolicitudPagov2(WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2Request request) {
            return base.Channel.ConsultarSolicitudPagov2(request);
        }
        
        public WSPlataforma.DA.PEWSGeneralReference.BEWSConsultarSolicitudResponse ConsultarSolicitudPagov2(WSPlataforma.DA.PEWSGeneralReference.BEWSConsultarSolicitudRequest request) {
            WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2Request inValue = new WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2Request();
            inValue.Body = new WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2RequestBody();
            inValue.Body.request = request;
            WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2Response retVal = ((WSPlataforma.DA.PEWSGeneralReference.ServiceSoap)(this)).ConsultarSolicitudPagov2(inValue);
            return retVal.Body.ConsultarSolicitudPagov2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2Response> WSPlataforma.DA.PEWSGeneralReference.ServiceSoap.ConsultarSolicitudPagov2Async(WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2Request request) {
            return base.Channel.ConsultarSolicitudPagov2Async(request);
        }
        
        public System.Threading.Tasks.Task<WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2Response> ConsultarSolicitudPagov2Async(WSPlataforma.DA.PEWSGeneralReference.BEWSConsultarSolicitudRequest request) {
            WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2Request inValue = new WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2Request();
            inValue.Body = new WSPlataforma.DA.PEWSGeneralReference.ConsultarSolicitudPagov2RequestBody();
            inValue.Body.request = request;
            return ((WSPlataforma.DA.PEWSGeneralReference.ServiceSoap)(this)).ConsultarSolicitudPagov2Async(inValue);
        }
    }
}
